services:
  - type: web
    name: meetspace-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run prisma:generate && npm run build:api
    startCommand: npm run start:api
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
